DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS temperature;
DROP TABLE IF EXISTS rgb;
DROP TABLE IF EXISTS timer;
DROP TABLE IF EXISTS holiday;
DROP TABLE IF EXISTS stock;


CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE temperature (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  value REAL NOT NULL
);

CREATE TABLE rgb (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    red REAL NOT NULL,
    green REAL NOT NULL,
    blue REAL NOT NULL
);

CREATE TABLE timer (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_closed BOOL NOT NULL DEFAULT TRUE,
  value REAL NOT NULL
);

CREATE TABLE holiday (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_away BOOL NOT NULL DEFAULT FALSE,
  value REAL NOT NULL
);

CREATE TABLE stock (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  product_name VARCHAR(64) NOT NULL,
  quantity NUMERIC(5) NOT NULL,
  product_expiration_date TIMESTAMP NOT NULL,
  shelf_number NUMERIC(5) NOT NULL

);